language: node_js
node_js:
  - node
  - lts/*
before_script:
  - npm run vendor
env:
  matrix:
    - FAST_HANDSHAKESTATE=1 TEST_SUITE=test-implementation
    - TEST_SUITE=test-vector
script: npm run $TEST_SUITE
